src/AppBundle/Entity/PagoAsignacion.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use AppBundle\Entity\ClienteProveedor;

/**
 * @ORM\Entity(repositoryClass="AppBundle\Entity\PagoAsignacionRepository")
 * @ORM\Table(name="pagoasignacion")
 */
class PagoAsignacion {

    CONST FACTURA = 'Factura';
    CONST FACTURA_PROVEEDOR = 'Factura proveedor';
    CONST NOTA_CREDITO = 'Nota de crédito';
    CONST NOTA_DEBITO = 'Nota de débito';
    CONST RECIBO_CLIENTE = 'Recibo cliente';
    CONST ORDEN_PAGO = 'Orden de pago';
    CONST GASTO = 'Gasto';

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    protected $importe;

    /**
     * @ORM\ManyToOne(targetEntity="Pago", inversedBy="pagosAsignacion")
     * @ORM\JoinColumn(name="pago_id", referencedColumnName="id", nullable=true)
     */
    protected $pago;

    /**
     * @ORM\ManyToOne(targetEntity="Gasto", inversedBy="pagosAsignacion")
     * @ORM\JoinColumn(name="gasto_id", referencedColumnName="id", nullable=true)
     */
    protected $gasto;

    /**
     * @ORM\ManyToOne(targetEntity="Cobranza", inversedBy="pagosAsignacionCobranza")
     * @ORM\JoinColumn(name="cobranza_id", referencedColumnName="id", nullable=true)
     */
    protected $cobranza;

    /**
     * @ORM\ManyToOne(targetEntity="Factura", inversedBy="pagosAsignacion")
     * @ORM\JoinColumn(name="factura_id", referencedColumnName="id", nullable=true)
     */
    protected $factura;

    /**
     * @ORM\ManyToOne(targetEntity="Consignacion", inversedBy="pagosAsignacion")
     * @ORM\JoinColumn(name="consignacion_id", referencedColumnName="id", nullable=true)
     */
    protected $consignacion;

    /**
     * @ORM\ManyToOne(targetEntity="NotaCreditoDebito", inversedBy="pagosAsignacion")
     * @ORM\JoinColumn(name="notacreditodebito_id", referencedColumnName="id", nullable=true)
     */
    protected $notaCreditoDebito;

    /**
     * @ORM\ManyToOne(targetEntity="ClienteProveedor", inversedBy="pagosAsignacion")
     * @ORM\JoinColumn(name="clienteproveedor_id", referencedColumnName="id", nullable=true)
     */
    protected $clienteProveedor;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $fecha;

    /**
     * @ORM\Column(type="string", length=1)
     */
    protected $estado = 'A';

    /*     * ********************************
     * __construct
     *
     *
     * ******************************** */

    public function __construct() {
        
    }

    /*     * ********************************
     * __toString()
     *
     * Este método sirve para poder popular los comboboxes en los forms.
     * ******************************* */

    public function __toString() {
        return $this->gasto . $this->pago . $this->factura . $this->cobranza . $this->notaCreditoDebito;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId() {
        return $this->id;
    }

    public function getDocumentName() {
        if (!is_null($this->factura)) {
            if ($this->factura->getTipo() == "F") {
                return self::FACTURA;
            } else {
                return self::FACTURA_PROVEEDOR;
            }
        }

        if (!is_null($this->notaCreditoDebito)) {

            if ($this->notaCreditoDebito->getTiponota() == NotaCreditoDebito::TIPO_CREDITO) {
                return self::NOTA_CREDITO;
            } else {
                return self::NOTA_DEBITO;
            }
        }
        if (!is_null($this->pago)) {
            return self::ORDEN_PAGO;
        }
        if (!is_null($this->cobranza)) {
            return self::RECIBO_CLIENTE;
        }

        if (!is_null($this->gasto)) {
            return self::GASTO;
        }
    }

    public function getDocument() {

        if (!is_null($this->factura)) {
            if ($this->factura->getTipo() == "F") {
                return (object) ['documento' => $this->factura, 'tipo' => self::FACTURA];
            } else {
                return (object) ['documento' => $this->factura, 'tipo' => self::FACTURA_PROVEEDOR];
            }
        }
        if (!is_null($this->notaCreditoDebito)) {
            if ($this->notaCreditoDebito->getTiponota() == NotaCreditoDebito::TIPO_CREDITO) {
                return (object) ['documento' => $this->notaCreditoDebito, 'tipo' => self::NOTA_CREDITO];
            } else {
                return (object) ['documento' => $this->notaCreditoDebito, 'tipo' => self::NOTA_DEBITO];
            }
        }
        if (!is_null($this->pago)) {
            return (object) ['documento' => $this->pago, 'tipo' => self::ORDEN_PAGO];
        }
        if (!is_null($this->cobranza)) {
            return (object) ['documento' => $this->cobranza, 'tipo' => self::RECIBO_CLIENTE];
        }
        if (!is_null($this->gasto)) {
            return (object) ['documento' => $this->gasto, 'tipo' => self::GASTO];
        }
    }

    /*
     * 
     */

    public function getBaseDocumentPath() {

        if (!is_null($this->factura)) {
            if ($this->factura->getTipo() == "F") {
                return 'factura';
            } else {
                return 'facturaproveedor';
            }
        }

        if (!is_null($this->notaCreditoDebito)) {
            if ($this->notaCreditoDebito->getClienteProveedor()->getClienteProveedor()==ClienteProveedor::CLIENTE_COD){
                return 'notacreditodebito';
            }else{
                return 'notacreditodebito_proveedor';
            }
            
        }
        if (!is_null($this->pago)) {
            return 'pago';
        }
        if (!is_null($this->cobranza)) {
            return 'cobranza';
        }
        if (!is_null($this->gasto)) {
            return 'gasto';
        }
    }

    /*
     * 
     */

    public function isDebit() {
        switch ($this->getDocumentName()) {
            case self::FACTURA:
                return true;
            case self::FACTURA_PROVEEDOR:
                return false;
            case self::GASTO:
                return false;
            case self::ORDEN_PAGO:
                return true;
            case self::NOTA_CREDITO:
                if ($this->clienteProveedor->getClienteProveedor() == ClienteProveedor::CLIENTE_COD) {
                    return false;
                } else {
                    return true;
                }
            case self::NOTA_DEBITO:
                if ($this->clienteProveedor->getClienteProveedor() == ClienteProveedor::CLIENTE_COD) {
                    return true;
                } else {
                    return false;
                }
            case self::RECIBO_CLIENTE:
                return false;
        }
    }

    /* public function getDocumento() {
      if ($this->factura) {
      $positivo = ($this->factura->getTipo() == "F") ? false : true;
      $tipo = ($this->factura->getTipo() == "FP") ? "facturaproveedor" : "factura";
      return array("entity" => $this->factura, "tipo" => $tipo, "positivo" => $positivo);
      }
      if ($this->consignacion) {
      return array("entity" => $this->consignacion, "tipo" => "consignacion", "positivo" => true);
      }
      if ($this->cobranza) {
      return array("entity" => $this->cobranza, "tipo" => "cobranza", "positivo" => true);
      }
      if ($this->pago) {
      return array("entity" => $this->pago, "tipo" => "pago", "positivo" => false);
      }
      if ($this->gasto) {
      return array("entity" => $this->gasto, "tipo" => "gasto", "positivo" => false);
      }
      if ($this->notaCreditoDebito) {
      $positivo = $this->notaCreditoDebito->getTiponota() == NotaCreditoDebito::TIPO_CREDITO ? true : false;
      return array("entity" => $this->notaCreditoDebito, "tipo" => "notaCreditoDebito", "positivo" => $positivo);
      }
      } */

    /**
     * Set importe
     *
     * @param float $importe
     * @return PagoAsignacion
     */
    public function setImporte($importe) {
        $this->importe = $importe;

        return $this;
    }

    /**
     * Get importe
     *
     * @return float
     */
    public function getImporte() {
        return $this->importe;
    }

    /**
     * Set estado
     *
     * @param string $estado
     * @return PagoAsignacion
     */
    public function setEstado($estado) {
        $this->estado = $estado;

        return $this;
    }

    /**
     * Get estado
     *
     * @return string
     */
    public function getEstado() {
        return $this->estado;
    }

    /**
     * Set pago
     *
     * @param \AppBundle\Entity\Pago $pago
     * @return PagoAsignacion
     */
    public function setPago(\AppBundle\Entity\Pago $pago = null) {
        $this->pago = $pago;

        return $this;
    }

    /**
     * Get pago
     *
     * @return \AppBundle\Entity\Pago
     */
    public function getPago() {
        return $this->pago;
    }

    /**
     * Set gasto
     *
     * @param \AppBundle\Entity\Gasto $gasto
     * @return PagoAsignacion
     */
    public function setGasto(\AppBundle\Entity\Gasto $gasto = null) {
        $this->gasto = $gasto;

        return $this;
    }

    /**
     * Get gasto
     *
     * @return \AppBundle\Entity\Gasto
     */
    public function getGasto() {
        return $this->gasto;
    }

    /**
     * Set factura
     *
     * @param \AppBundle\Entity\Factura $factura
     * @return PagoAsignacion
     */
    public function setFactura(\AppBundle\Entity\Factura $factura = null) {
        $this->factura = $factura;

        return $this;
    }

    /**
     * Get factura
     *
     * @return \AppBundle\Entity\Factura
     */
    public function getFactura() {
        return $this->factura;
    }

    /**
     * Set notaCreditoDebito

src/AppBundle/Form/PagoAsignacionType.php
<?php

namespace AppBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class PagoAsignacionType extends AbstractType
{
        /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('importe')
            ->add('estado')
            ->add('pago')
            ->add('gasto')
            ->add('factura')
            ->add('notaCreditoDebito')
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\PagoAsignacion'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'app_bundle_pagoasignacion';
    }
}

src/AppBundle/Resources/views/PagoAsignacion/PagoAsignacion.twig
{% extends 'AppBundle::base.html.twig' %}
{% block content -%}
    <h2 style="margin-bottom:10px;">
        Informe de Movimientos       
    </h2>
    <hr/>
    {% include 'AppBundle:PagoAsignacion:buscadorInforme.html.twig' %}
    <hr />
    <div class="gestion">       
        <table id="tablaInformeMovimientos" class="display" width="100%">
            <thead>
                <tr>
                    <th>Fecha</th>
                    <th>Documento</th>
                    <th>Cliente/Proveedor</th>                             
                    <th>Medios</th>
                    <th>Cheques</th>
                        {% if is_granted('ROLE_SUPER_ADMIN') %}
                        <th>Unidad de Negocio</th>
                        {% endif %}
                    <th>Importe($)</th>
                </tr>
            </thead>
            <tbody>
                {% for entity in entities %}                
                    <tr>
                        <td>{{ entity.fecha|date('Y-m-d') }}</td>
                        <td>
                            <a href="{{ path(entity.documento.tipo~'_show', { 'id': entity.documento.entity.id }) }}">{{ entity.documento.entity }}</a>
                        </td>
                        <td>
                            <a title="Cuenta Corriente" href="{{ path('pagoasignacion', { 'id': entity.documento.entity.clienteProveedor.id }) }}">{{ entity.documento.entity.clienteProveedor }}</a>
                        </td>                    
                        <td>
                            {% if  entity.documento.entity.medios  is defined %}
                                {% for medioPago in entity.documento.entity.medios  %}   
                                    {% if app.request.get('medio')!='cheque' and app.request.get('medio') !='' and app.request.get('medio')== medioPago.medio.id %}
                                        {{ medioPago.medio.descripcion }} - $ {{ medioPago.importe }}
                                        <br>
                                    {% endif %}
                                    {% if app.request.get('medio')!='cheque' and app.request.get('medio') ==''%}
                                        {{ medioPago.medio.descripcion }} - $ {{ medioPago.importe }}                                       
                                        <br>
                                    {% endif %}
                                {% endfor %}
                            {% else %}
                                -
                            {% endif %}
                        </td>
                        <td>
                            {% if  entity.documento.entity.cheques is defined %}
                                {% for cheque in entity.documento.entity.cheques if cheque.estado!='E' %} 
                                    <a href="{{ path('cheque_show', { 'id': cheque.id }) }}" target="_blank">{{ cheque }} - $ {{ cheque.importe }}</a>                           
                                    <br>                                    
                                {% endfor %}
                            {% else %}
                                -
                            {% endif %}
                        </td>
                        {% if is_granted('ROLE_SUPER_ADMIN') %}
                            <td>{{ entity.documento.entity.unidadNegocio }}</td>
                        {% endif %}
                        <td>$ {{ entity.importe }}</td>
                    </tr>               
                {% endfor %}
            </tbody>                     
        </table>
    </div>
    <div class="col-sm-12">        
        {{ pagerfanta (entities, 'twitter_bootstrap_translated' , { 'prev_message' : 'Anterior', 'next_message': 'Siguiente'} ) }}
    </div>
    <script>
        $(function () {
            $('#tablaInformeMovimientos').DataTable({
                "scrollY": "400px",
                "scrollCollapse": true,
                "paging": false,
                "info": false,
                responsive: true,
                "filter": false,
                "order": []
            });
            $('td').css('padding', '2px');


        });
    </script>
    <style>
        .active .btn
        {
            background-color: #9E9E9E;
        }
        ul{
            list-style: none;
        }
    </style>

{% endblock %}

src/AppBundle/Resources/views/PagoAsignacion/buscadorInforme.html.twig
<!-- Buscador -->
<div class="container" style="margin-bottom: 2%;">
    <form action="{{ path('pagoasignacion_informe') }}" method="GET">
        <div class="row">
            <div class="col-md-3">
                <label>Fecha desde</label>
                <input type="date" value="{{app.request.get('fechaDesde')|default('NOW -30 days'|date('Y-m-d'))}}" class="form-control" name="fechaDesde" placeholder="Fecha desde">
            </div>
            <div class="col-md-3">
                <label>Fecha hasta</label>
                <input type="date" value="{{app.request.get('fechaHasta')|default('NOW'|date('Y-m-d'))}}" name="fechaHasta" placeholder="Fecha hasta">
            </div>
            <div class="col-md-3">
                <label>Medio</label>
                <select name="medio" class="col-xs-12" id="medio">              
                    {{ render(controller('AppBundle:Medio:renderSelect', {'estado':'A'})) }}                                                                          
                </select>
            </div>
            <div class="col-md-3">
                <label>Tipo de Movimiento</label>
                <select name="tipoMovimiento" class="col-xs-12" id="tipoMovimiento">              
                    <option value="">Tipos de movimientos</option>
                    <option value="cobranza">Cobranza</option>
                    <option value="compra">Compra</option>
                    <option value="gasto">Gasto</option>
                    <option value="pago">Pago</option>
                    <option value="credito">Nota de Cr&eacute;dito/D&eacute;bito</option>
                    <option value="venta">Venta</option>
                </select>
            </div>        
        </div>
        <br>
        <div class="row">
            <div class="col-md-4">
                <label>Cliente</label>
                <select name="cliente" class="col-xs-12" id="cliente">              
                    {{ render(controller('AppBundle:ClienteProveedor:renderSelect', {'estado':'A','clienteProveedor':'1'})) }}                                                                          
                </select>
            </div>
            <div class="col-md-4">
                <label>Proveedor</label>
                <select name="proveedor" class="col-xs-12" id="proveedor">              
                    {{ render(controller('AppBundle:ClienteProveedor:renderSelect', {'estado':'A','clienteProveedor':'2'})) }}                                                                          
                </select>
            </div>
            {% if is_granted('ROLE_SUPER_ADMIN') %}
                <div class="col-md-4">
                    <label>Unidad de Negocio</label>
                    <select name="unidadNegocio" class="col-xs-12" id="unidadNegocio">              
                        {{ render(controller('AppBundle:UnidadNegocio:renderSelect', {'estado':'A'})) }}                                                                          
                    </select>
                </div>
            {% endif %}
        </div>
        <br>
        <div class="row">           
            <div class="col-xs-12" >                
                <button class="btn btn-info" type="submit" id="buscar" name="action" value="buscar">
                    Buscar
                </button>
                <button class="btn btn-success pull-right" id="generar"  type="submit" name="action" value="excel">
                    <i class="fa fa-file-excel-o"> Exportar Excel </i>    
                </button>
            </div>
        </div>
    </form>
</div>
<script>
    $(function () {
        $('#generar').unbind("click"); //Permite que no se carge el spinner y que pueda descargar el excel
        var medio = '{{app.request.get('medio')}}';
        $('#medio').val(medio).change();
        var unidadNegocio = '{{app.request.get('unidadNegocio')}}';
        $('#unidadNegocio').val(unidadNegocio).change();
        var cliente = '{{app.request.get('cliente')}}';
        $('#cliente').val(cliente).change();
        var proveedor = '{{app.request.get('proveedor')}}';
        $('#proveedor').val(proveedor).change();
        var tipoMovimiento = '{{app.request.get('tipoMovimiento')}}';
        $('#tipoMovimiento').val(tipoMovimiento).change();
    });
</script>

src/AppBundle/Resources/views/PagoAsignacion/buscadorInformeIngresoEgreso.html.twig
<!-- Buscador -->
<div class="container" style="margin-bottom: 2%;">
    <form action="{{ path('pagoasignacion_ingresoegreso') }}" method="GET">
        <div class="row">
            <div class="col-md-3">
                <label>Fecha desde</label>
                <input type="date" value="{{app.request.get('fechaDesde')|default('NOW -30 days'|date('Y-m-d'))}}" class="form-control" name="fechaDesde" placeholder="Fecha desde">
            </div>
            <div class="col-md-3">
                <label>Fecha hasta</label>
                <input type="date" value="{{app.request.get('fechaHasta')|default('NOW'|date('Y-m-d'))}}" name="fechaHasta" placeholder="Fecha hasta">
            </div>
            <div class="col-md-3">
                <label>Medio</label>
                <select name="medio" class="col-xs-12" id="medio">              
                    {{ render(controller('AppBundle:Medio:renderSelect', {'estado':'A'})) }}                                                                          
                </select>
            </div>
            {% if is_granted('ROLE_SUPER_ADMIN') %}
                <div class="col-md-3">
                    <label>Unidad de Negocio</label>
                    <select name="unidadNegocio" class="col-xs-12" id="unidadNegocio">              
                        {{ render(controller('AppBundle:UnidadNegocio:renderSelect', {'estado':'A'})) }}                                                                          
                    </select>
                </div>
            {% endif %}
        </div>
        <br>
        <div class="row">
            <div class="col-md-4">
                <label>Cliente</label>
                <select name="cliente" class="col-xs-12" id="cliente">              
                    {{ render(controller('AppBundle:ClienteProveedor:renderSelect', {'estado':'A','clienteProveedor':'1'})) }}                                                                          
                </select>
            </div>
            <div class="col-md-4">
                <label>Proveedor</label>
                <select name="proveedor" class="col-xs-12" id="proveedor">              
                    {{ render(controller('AppBundle:ClienteProveedor:renderSelect', {'estado':'A','clienteProveedor':'2'})) }}                                                                          
                </select>
            </div>
            <div class="col-md-4">
                <label>Tipo de Movimiento</label>
                <select name="tipoMovimiento" class="col-xs-12" id="tipoMovimiento">              
                    <option value="">Tipos de movimientos</option>
                    <option value="cobranza">Cobranza</option>                   
                    <option value="pago">Pago</option>                   
                </select>
            </div>
        </div>
        <br>
        <div class="row">           
            <div class="col-xs-12" >                
                <button class="btn btn-info" type="submit" id="buscar" name="action" value="buscar">
                    Buscar
                </button>
                <button class="btn btn-success pull-right" id="generar"  type="submit" name="action" value="excel">
                    <i class="fa fa-file-excel-o"> Exportar Excel </i>    
                </button>
            </div>
        </div>
    </form>
</div>
<script>
    $(function () {
        $('#generar').unbind("click"); //Permite que no se carge el spinner y que pueda descargar el excel
        var medio = '{{app.request.get('medio')}}';
        $('#medio').val(medio).change();
        var unidadNegocio = '{{app.request.get('unidadNegocio')}}';
        $('#unidadNegocio').val(unidadNegocio).change();
        var cliente = '{{app.request.get('cliente')}}';
        $('#cliente').val(cliente).change();
        var proveedor = '{{app.request.get('proveedor')}}';
        $('#proveedor').val(proveedor).change();
        var tipoMovimiento = '{{app.request.get('tipoMovimiento')}}';
        $('#tipoMovimiento').val(tipoMovimiento).change();
    });
</script>

src/AppBundle/Resources/views/PagoAsignacion/index.html.twig
{% extends 'AppBundle::base.html.twig' %}

{% block content -%}
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">Cuenta Corriente de {{ clienteProveedor.razonSocial }}

            </h2>
        </div>
    </div>
    {% include 'AppBundle:PagoAsignacion:seeker.html.twig' %}    
    <div class="row text-center oculto">
        <hr>
        <div class="col-md-8">
            <button style="margin-left: -5px;" class="btn btn-info" id="print">
                Imprimir
            </button>            
            <a class="btn btn-sm btn-primary"  href="{{path('notacreditodebito_new',{'id_clienteproveedor':clienteProveedor.id,'tipo':constant('AppBundle\\Entity\\NotaCreditoDebito::TIPO_DEBITO')})}}">Nota de D&eacute;bito</a>
            <a class="btn btn-sm btn-info" href="{{path('notacreditodebito_new',{'id_clienteproveedor':clienteProveedor.id,'tipo':constant('AppBundle\\Entity\\NotaCreditoDebito::TIPO_CREDITO')})}}">Nota de Cr&eacute;dito</a>                            
            {% if clienteProveedor.clienteproveedor ==constant('AppBundle\\Entity\\ClienteProveedor::CLIENTE_COD') %}
                <button class="btn btn-warning" id="cobrarseleccionados">
                    Cobrar seleccionados
                </button>
            {% else %}
                <button class="btn btn-warning" id="pagarseleccionados">
                    Pagar seleccionados
                </button>
            {% endif %}
        </div>
        <div class="col-md-4">
            <a style="margin-right: 1em;" class="btn btn-primary btn-xs" href="{{ path('clienteproveedor_show', {id: clienteProveedor.id}) }}">
                <i class="fa fa-user"></i> Ver Datos
            </a>
            <a style="margin-left: -5px;" class="btn btn-warning btn-xs" href="{{ path('clienteproveedor') }}">
                Volver al listado
            </a>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-xs-6">
            Saldo Inicial $: {{ clienteProveedor.saldo }}
        </div>
        <div class="col-xs-6">
            <span class="float-right" >Saldo Actual ($):
                <span>                     
                    {{  PagoAsignacionService.getBalance(clienteProveedor.id)}}                    
                </span>
            </span>                                
        </div>
    </div>

    <div class="row" style="padding: 1rem;" >
        <div class="table-responsive">     
            <form method="POST" action="{{ path(clienteProveedor.clienteproveedor == constant('AppBundle\\Entity\\ClienteProveedor::CLIENTE_COD') ? 'cobranza_new' : 'pago_new') }}" id="formCuentas">
                <table id="tablaCheques" class="table table-bordered" data-toggle="table"  data-show-columns="true" cellspacing="0">
                    <thead>
                        <tr>       
                            <th ></th> 
                            <th >Fecha</th>     
                            <th >Movimiento</th>                                                                           
                            <th >D&eacute;bito</th> 
                            <th >Cr&eacute;dito</th>                                                         
                            <th >Saldo</th>                            
                        </tr>
                    </thead>
                    <tbody>                        
                        {% if movimientoscc|length > 0 %}
                            {% for movimientocc in movimientoscc %}
                                {% set documento = movimientocc.document.documento %}

                                <tr >                                           
                                    <td>
                                        {% if movimientocc.documentname == constant('AppBundle\\Entity\\PagoAsignacion::FACTURA') or  movimientocc.documentname == constant('AppBundle\\Entity\\PagoAsignacion::FACTURA_PROVEEDOR') %}
                                            <input type="checkbox" style="height: 1em;" name="idfacturas[]" value="{{documento.id }}" />
                                        {% endif %}
                                    </td>
                                    <td>{{ documento.fecha|date('d-m-Y') }}</td>          
                                    <td>                                        
                                        <a href="{{ path(movimientocc.baseDocumentPath~'_show',{'id':documento.id}) }}" target="_blank">
                                            {{documento| raw }}
                                        </a>
                                         {% if (movimientocc.documentname == constant('AppBundle\\Entity\\PagoAsignacion::NOTA_CREDITO') or movimientocc.documentname == constant('AppBundle\\Entity\\PagoAsignacion::NOTA_DEBITO')) and documento.cae == ''  %}
                                        <a class="btn btn-success" href="{{ path('notacreditodebito_refacturar', { 'id': documento.id}) }}">
                                            <i class="fa fa-spin fa-refresh"></i>
                                        </a>
                                    {% endif %}
                                        
                                    </td>
                                    <td>
                                        {% if movimientocc.isDebit %}
                                            {{  movimientocc.importe}}
                                        {% endif %}
                                    </td>                                                             
                                    <td>
                                        {% if not movimientocc.isDebit %}
                                            {{  movimientocc.importe}}
                                        {% endif %}
                                    </td>
                                    <td>
                                        {{  PagoAsignacionService.getParcialBalance(movimientocc.id)}}
                                    </td>                                   
                                </tr>   
                            {% endfor %}
                        {% else %}
                            <tr>                               
                                <td colspan="5" >No registra movimientos</td>                                
                            </tr>
                        {% endif %}
                    </tbody>
                </table>
            </form>
            <div class="col-sm-12">
                {{ pagerfanta (movimientoscc, 'twitter_bootstrap_translated' , { 'prev_message' : 'Anterior', 'next_message': 'Siguiente'} ) }}
            </div>
        </div>

    </div>

</div>     
<style>
    .active .btn
    {
        background-color: #9E9E9E;
    }
    ul
    {
        list-style: none;
    }
</style>
<script>
    $(function () {
        $("#cobrarseleccionados, #pagarseleccionados").click(function () {
            var checked = false;
            $('input[type=checkbox]').each(function () {
                if (this.checked) {
                    checked = true;
                }
            });
            if (checked) {
                $("#formCuentas").submit();
            }
        });
    });
</script>	
{% endblock %}